rockets-list : génère une liste des messages Slack contentant une 🚀
sgmap/beta.wip pull request #3
Opened 2017-05-26 15:09 UTC by kemenaran

Ajoute un script pour générer une liste des messages Slack contentant une `:rocket:` (cf. https://github.com/sgmap/beta.gouv.fr/issues/612)

Cet script peut être utilisé pour générer manuellement un récapitulatif des dernières rockets, à copier-coller dans une newsletter.

Le script nécessite une clef d'API Slack (à créer sur https://api.slack.com/custom-integrations/legacy-tokens)

Exemple :

```
$ SLACK_API_TOKEN=<token> ./rockets-to-text.rb
22/05/2017 - @samuel_faure
réussi a installer le backend sirene-entreprise rails 100% sans accroc depuis le ansible sur VM (le fait que ce soit sur VM a rendu le truc un peu tricky)

19/05/2017 - @julien
Lancement Dimanche par Dijon de leur programme de végétalisation participative : http://jadopteunarbre.dijon.fr/ ( accompagné par Plante Et Moi )

18/05/2017 - @mattisg
Mise à jour de la fiche sur https://api.gouv.fr/api/openfisca.
Au passage, avez-vous bien rajouté une “star” sur les 6 dépôts qui sont mis en avant sur https://github.com/openfisca ?  :smile:

17/05/2017 - @floby
http://particulier-sandbox.api.gouv.fr|particulier-sandbox.api.gouv.fr !
```

@Morendil tu en penses quoi ?

2017-05-26 15:40 UTC, maukoquiroga commented on rockets-list.rb
> +if ENV['SLACK_API_TOKEN'] == nil
Peut-être dire plus explicitement que le token doit être présent ?

Example :

```ruby
unless ENV['SLACK_API_TOKEN'].present?
```

2017-05-29 08:28 UTC, kemenaran commented on rockets-list.rb
> +if ENV['SLACK_API_TOKEN'] == nil
Ça serait plus lisible, effectivement.

Seul pépin : `Object#present?` n'est pas une méthode de base de Ruby, c'est tiré de Rails (enfin, d'[ActiveSupport](http://guides.rubyonrails.org/active_support_core_extensions.html#blank-questionmark-and-present-questionmark)). Du coup ça nécessiterait de require une gem non standard dans ce script, donc de faire un Gemfile, donc… Bref, j'ai préféré garder le moins de dépendances possible :)

Tu vois une façon plus lisible d'écrire ça qui ne nécessiterait pas de gems externes ?

2017-05-29 12:01 UTC, maukoquiroga commented on rockets-list.rb
> +if ENV['SLACK_API_TOKEN'] == nil
Oups, bien vu ! Alors...

```ruby
if ENV['SLACK_API_TOKEN'].blank?
```

?

2017-05-29 12:10 UTC, bonjourmauko requested changes
Perso je trouve cool le script.

Deux pépins : 

1. En suivant le message d'erreur, j'arrive à la page de création de tokens mais je ne sais pas lequel dois-je créer.

<img width="755" alt="capture d ecran 2017-05-29 a 14 09 09" src="https://cloud.githubusercontent.com/assets/329236/26549270/6c2f4880-4478-11e7-8295-ab570556dd9d.png">

2. (optionnel) Peut-être que c'est plus claire de consolider la @doc complète au tout début du script (complémenter l'« usage » existant avec la création du token).

2017-06-08 10:56 UTC, MattiSG commented
Cool ! Ça aurait probablement du sens intégré avec un message hebdomadaire contenant ces messages. On en est où @kemenaran ? :wink:

2017-06-08 16:24 UTC, bonjourmauko approved these changes

2017-06-08 16:25 UTC, maukoquiroga commented
Je me suis trompé, ça marche avec les instructions. GTM for me.

2017-06-09 16:56 UTC, merged